### ISSUE TITLE
AttributeError: 'Pritunl' object has no attribute 'root'

### ISSUE THREAD

**Issue by zpol** [ijat/pritunl-api-python#1]
Traceback (most recent call last):
  File "/tmp/pritunl-api-python/pritunl_api/__init__.py", line 299, in ping
    raise PritunlErr("{0}:{1}".format(sys._getframe().f_code.co_name, self.root.BASE_URL))
AttributeError: 'Pritunl' object has no attribute 'root'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/pritunl-api-python/server.py", line 11, in <module>
    if pri.ping():
  File "/tmp/pritunl-api-python/pritunl_api/__init__.py", line 301, in ping
    raise PritunlErr("{0}:{1}".format(sys._getframe().f_code.co_name, self.root.BASE_URL))
AttributeError: 'Pritunl' object has no attribute 'root'

```
from pritunl_api import *

pri = Pritunl(url="https://pritunl.blah.cloud",
              token="xxxxxxx",
              secret="yyyyyyy")
if pri.ping():
    s = pri.server.get()
    print(s)
```

**Comment by zpol** [comment]
It just stop working a few days ago,....
